### ISSUE TITLE
VEGAS Pro 15 cannot open openfx-misc on

### ISSUE THREAD

**Issue by GlitchyPSIX** [NatronGitHub/openfx-misc#66]
Loading OFX plugins (Starting video plug-in factory, openfx-misc), VEGAS just crashes with Unhandled Exception (0x0000005), when using the builds from AppVeyor.

**Comment by rodlie** [comment]
I can confirm this on Vegas 12 as well (also tested with mingw binaries). Note that it's only Misc.ofx that crashes, CImg.ofx loads fine.

I also tested with Resolve 15 (mingw and your AppVeyor binaries) and everything is fine.


*Btw, I think OpenFX broke Vegas support some time ago. The plugins load, the parameters work, but you only get the source image in the viewer, or the render function never runs, I don't know. Can also confirm same behavior in openfx-arena (that at some point in time I used in Vegas 12). Not super important for me, but I though you should know.*

**Comment by GlitchyPSIX** [comment]
CImg.ofx loads fine, but the preview changes nothing
Loading the binaries included with Natron directly in the OFX folder will load everything but crash VEGAS upon trying to show an effect.

Also, was openfx-arena privated? I can't seem to be able to access it anymore.

Hitfilm works fine in both VEGAS and Natron by the way so something's up...

**Comment by devernay** [comment]
You mean "Vegas broke OpenFX support"?

Those crashes are usually tracked down using the ofx Log (which is enabled when compiling plugins in debug mode.

Sometimes (eg with Resolve) the ofx log doesn't work and the only way is to use printf, or to disable the code from the rendering functions (getROD, getROI, render) using #if 0 and then gradually re-enabling it until the crash appears.

Since the crash happens at launch time, my guess is that it's simply that one plugin tries to get a host property which doesn't exist on Vegas, and thus throws an exception. This is easily fixed by setting the second parameter of `propGet*()` to false. If someone finds out which property is not supported by Vegas, please write it here and I'll document that in https://github.com/NatronGitHub/openfx-misc/blob/master/README-hosts.txt

**Comment by devernay** [comment]
It would be nice to have the full host description for Vegas: compile the Rectangle plugin with `#define DEBUG_HOSTDESCRIPTION` enabled.

For testing purposes, build the plugins separately (make nomulti)

**Comment by GlitchyPSIX** [comment]
I'll try, recently went down and installed VC++E 2010 to build with VS as I'm not experienced with building from MinGW/Cygwin

**Comment by rodlie** [comment]
I was not referring to the crash when I wrote "OpenFX broke Vegas support". I was talking in general, since no plugins that uses https://github.com/NatronGitHub/openfx seems to do anything in Vegas anymore. They load, the parameters work,  but the render action seems to do nothing(?).

**Comment by devernay** [comment]
As I wrote before, it's probably simply because of an unsupported property in Vegas. The ofx log helps a lot in this case.

**Comment by rodlie** [comment]
sure, I will do it tomorrow (getting late here).

**Comment by rodlie** [comment]
Host description for Sony Vegas 12:
https://gist.github.com/rodlie/6ebf8e6d56f3a98e75e1fbca0bc90886

**Comment by GlitchyPSIX** [comment]
I may be doing something wrong, but now I can't find the log. (Compiled with MinGW, crashes upon selecting effect/generator)

**Comment by devernay** [comment]
Thanks @rodlie 
OpenFX 1.1...
Now do you think you can find the unknown property that causes that exception?
@GlitchyPSIX on my mac, Sony Catalyst Edit puts the OFX log in /Applications.ofxTestLog.txt, so it can be anywhere in the filesystem... Look for a file called "ofxTestLog.txt" after runnin the plugins compiled in debug mode. The next solution is to launch vegas from cmd.sys, and do some printfs in the code. For testing purposes, you should compile each plugin individually. Makefiles do that, but I don't think it's in the VC++ project

**Comment by GlitchyPSIX** [comment]
Yeah, the VC++ project doesn't have the option to build separately, so I went with using MinGW-64
I'll run VEGAS from cmd and give you results once I get something

**Comment by devernay** [comment]
You should try with the newest appveyor artifacts. I just fixed a major bug in the openfx Support lib and added more compatibility

**Comment by rodlie** [comment]
The plugins are loaded and detected here.

**Comment by GlitchyPSIX** [comment]
Loaded and detected, albeit the clicking/render crash issue is still present.

**Comment by devernay** [comment]
I don't have VEGAS, so I cannot check here.
What we could do is to be a LOT more permissive with regards to things that the host (Resolve, Fusion, VEGAS, etc) may do wrong. I will work on a version where the checking code is only enabled when compiling in DEBUG mode. This could also be the version included by default with Natron binaries.
So the code will be more fragile because it's still assuming that the host is behaving according to the OpenFX specs, but it will not crash on purpose as soon as it finds something wrong with the host (eg Resolve, Fusion, VEGAS, etc).
And we could distribute two versions as well: the debug version and the dirty version.

**Comment by GlitchyPSIX** [comment]
Please contact me directly, I can directly help with the "not having VEGAS" issue.

**Comment by rodlie** [comment]
Btw, I'm able to get plugins working in Vegas 12/14 if I don't check for renderScale in render (if host is com.sonycreativesoftware.vegas).

I skip ``if (!kSupportsRenderScale && (args.renderScale.x != 1. || args.renderScale.y != 1.)) {`` and ``if (srcImg->getRenderScale().x != args.renderScale.x ||...``

**Comment by devernay** [comment]
could you get the values for args.renderScale and srcImg->getRenderScale()?

**Comment by rodlie** [comment]
View Full:
kSupportsRenderScale: 0
renderScale.x: 1
renderScale.y: 1
srcImg->getRenderScale.x: 1
srcImg->getRenderScale.y: 1

View Auto:
kSupportsRenderScale: 0
renderScale.x: 0.25
renderScale.y: 0.25
srcImg->getRenderScale.x: 1
srcImg->getRenderScale.y: 1

View Full:
kSupportsRenderScale: 1
renderScale.x: 1
renderScale.y: 1
srcImg->getRenderScale.x: 1
srcImg->getRenderScale.y: 1

View Auto:
kSupportsRenderScale: 1
renderScale.x: 0.25
renderScale.y: 0.25
srcImg->getRenderScale.x: 1
srcImg->getRenderScale.y: 1

**Comment by devernay** [comment]
It should be fixed now, can you test?

**Comment by rodlie** [comment]
Sure, will take a couple of hours since I don't have access to my Vegas machine at the moment.

**Comment by devernay** [comment]
@rodlie can you check if it is fix, so that we can close this?

**Comment by GlitchyPSIX** [comment]
Using the latest AppVeyor builds crash VEGAS upon trying to open an effect still.

**Comment by devernay** [comment]
I cannot help much, but maybe @rodlie can have a look

**Comment by rodlie** [comment]
I don't have time to look into Vegas issues at the moment, maybe next week. Try building them one by one and check which (plugin) works or not.

Note that some interacts from openfx-supportext has issues in resolve/fusion/vegas. IMHO the OpenFX support in resolve/fusion/vegas is sub-par and requires workarounds to get working properly.

**Comment by Dragonslayer293** [comment]
I was redirected here by devernay, I think I may have the same issue. I have the plugins loaded into the ofx folder, but they will not show up in vegas (or resolve/fusion) I am very confused, did vegas mess something up when searching for the plugins?

![Screenshot (155)](https://user-images.githubusercontent.com/18077261/80892908-9ca64180-8c82-11ea-9e48-8f04fd68a009.png)
![Screenshot (156)](https://user-images.githubusercontent.com/18077261/80892910-9d3ed800-8c82-11ea-9ac7-e1d843c00a9f.png)
![Screenshot (157)](https://user-images.githubusercontent.com/18077261/80892911-9fa13200-8c82-11ea-8617-bb18e6ebd326.png)
![Screenshot (158)](https://user-images.githubusercontent.com/18077261/80892914-a039c880-8c82-11ea-8059-3d3da219e037.png)

**Comment by rodlie** [comment]
@Dragonslayer293 You can't use the binary plugins included with Natron in other applications. They require several DLL's only included with Natron. You can however find openfx-misc binaries compatible with other applications here: https://ci.appveyor.com/project/NatronGitHub/openfx-misc/build/artifacts

Note that Vegas support is a hit or miss on some plugins. Most plugins that don't use a overlay/interact should work in Vegas/Resolve/Fusion.

**Comment by devernay** [comment]
Interacts work fine in Resolve on macOS, so I guess they work fine in Fusion too.

**Comment by Dragonslayer293** [comment]
@rodlie That was magic, it worked thanks, I have noticed there are some plugins in natron that arent in their. Are those just not compatible with vegas? IE: GLSL  In "natron-plugins-master"

those are some of the ones i was hoping could work, if not thats ok though

**Comment by devernay** [comment]
@Dragonslayer293  Those are PyPlugs, not OpenFX plugins. You can tray to rebuild these using the Shadertoy plugin, if it works in Vegas, but  I doubt it

**Comment by devernay** [comment]
It may be fixed see  https://github.com/NatronGitHub/openfx-misc/issues/75
@GlitchyPSIX can you please try with recent artifacts from https://ci.appveyor.com/project/NatronGitHub/openfx-misc/build/artifacts ?
If it's still not working, I'll leave this open, else I'll close it.

**Comment by GlitchyPSIX** [comment]
> It may be fixed see #75
> @GlitchyPSIX can you please try with recent artifacts from https://ci.appveyor.com/project/NatronGitHub/openfx-misc/build/artifacts ?
> If it's still not working, I'll leave this open, else I'll close it.

Some things have changed.

- some Generated Media now displays a preview instead of crashing on sight
    - PlasmaCImg however crashed after clicking on a few of the generated media (without adding it to timeline)
- some Effects work (Bit of weird controls, but usable, are some of the FX composite modes? They're showing as effects.)
    - CImg effects crash

**Comment by devernay** [comment]
Any hint on the crash reason, like a backtrace for example?

**Comment by GlitchyPSIX** [comment]
I can't seem to be able to find any hint in the logs VEGAS presents in the "More Information" log files...
